apiVersion: v1
kind: Service
metadata:
  name: devchan-modresortchan-service
  labels:
    app: modresortchan
spec:
  type: LoadBalancer
  selector:
      app: modresortchan
      release: modresort-devchan
      tier: frontend
