apiVersion: v1
kind: Service
metadata:
  name: devchan-modresortchan-service
  labels:
    app: modresortchan
spec:
  type: NodePort
  ports:
    - nodePort: 31456
  selector:
      app: modresortchan
      release: modresort-devchan
      tier: frontend
