apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: devchan-modresortchan-route
  name: modresorts
spec:
  host: testfra23-june9-68911-bf71d5c157aa98b6c96891f5d1f815dc-0000.us-south.containers.appdomain.cloud
  port:
    targetPort: 9080
  to:
    kind: Service
    name: devchan-modresortchan-service
    weight: 100
  wildcardPolicy: None
